baseURL = 'https://daabin.github.io/'
languageCode = ''
title = '王东坡#29'
theme = 'archie'

[[menu.main]]
name = "最新"
url = "/"
weight = 1

[[menu.main]]
name = "全部"
url = "/posts"
weight = 2

[[menu.main]]
name = "标签"
url = "/tags"
weight = 3

[[menu.main]]
name = "简介"
url = "/about"
weight = 4

